name: Test trigger

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "It works!"